// GENERATED by tools/gen_shards.py -- do not edit, regenerate; arm group 0.

#include "carry/carry_arm.cuh"
#include "carry_selection.inc"

namespace rola::carry {

#if defined(ROLA_CARRY_BUILD_0)
ROLA_CARRY_ARM_DEFINE(0, 2, 64, 8)
#endif

}  // namespace rola::carry
