"""THE ONE ENUMERATION of the carry family's instantiation matrix.

**WHAT THIS OWNS.** ONE closed-world arm list is DEFINED ONCE here -- `CARRY_ARMS`,
the carry family's rows -- and everything that enumerates it is GENERATED from that
definition: one translation unit per arm under `csrc/rola/src/instantiations/`
(KERNEL_STANDARDS section 7, which is what makes an arm-subset build a FILE subset
and lets the arms compile in parallel instead of serially inside one `cicc`), and
`build/generated/carry_selection.inc`, the never-checked-in per-run header naming
which of those rows this build or ratify run actually carries.

Two independent enumerations of one set is the drift shape this project has already
been bitten by (the shared-router bug), so the list, the macros and the units all
come from `CARRY_ARMS`.

**THE MEMBERSHIP IS A DECLARATION, THE ENUMERATION IS THIS FILE.** The rows
themselves live in `tools/manifests/shipped_set.json` -- the declared shipped set,
as DATA -- and this module reads, refuses and enumerates them.  A shipped set is a
statement about the PRODUCT (which `(D, DV, warps_per_cta)` a wheel carries), so it
is reviewable on its own and readable without importing anything; what a row MEANS,
which translation unit carries it, what the selection header and the ratification's
shard block say about it, is code and lives here.  `setup.py`'s post-build check
re-reads the declaration and asserts the table still matches it.

**THE LIST IS EMPTY ON THIS LINE.** The carry family's kernels are deleted and the
stats passes with them (card C, `development/queue/C_CLEAN_SLATE.md`), so the
declaration declares no arm and this generator emits NO file: there is no arm, no
per-arm unit and no instantiation directory.  What survives is the BUILD's contract
-- the table, its final `(D, DV, warps_per_cta)` key, the shipped/test split, the
selection header and the arm set `arm_switch` dispatches over -- because `setup.py`
and `tools/ratify.py` speak it on every run whether or not a row exists.

The generated files are CHECKED IN, not built: what is reviewed is what compiles
(closed-world codegen policy). `--check` regenerates into memory and diffs, which is
what CI and `tools/lint/lint_standards.py` run.

Usage:

    python tools/gen_shards.py --write      # regenerate the tree
    python tools/gen_shards.py --check      # regenerate into memory and diff (CI)
    python tools/gen_shards.py --self-test  # prove the declaration reader refuses
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import host_budget  # noqa: E402 -- path insert must precede this import

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "csrc" / "rola" / "src" / "instantiations"

#: THE DECLARED SHIPPED SET, AS DATA.  The arm table below is READ from this
#: file, never written here: a shipped set is a DECLARATION about the product -- which
#: (D, DV, warps_per_cta) a user's wheel carries -- and a declaration that can only be
#: read by importing a code module is one a reviewer, a packager and the post-build
#: check each have to execute to see.  As data it is diffable, reviewable in a pull
#: request on its own, and readable by a tool that must not import anything (the 14th
#: extension-trap form: a repo tool reads the repo's files, it does not import the
#: package to learn a fact about the repo).  `setup.py`'s post-build check asserts the
#: table this module exposes still MATCHES the declaration, which is what makes the
#: two independent statements rather than one restated twice.
SHIPPED_SET_JSON = ROOT / "tools" / "manifests" / "shipped_set.json"

#: THE GENERATED (NEVER CHECKED IN) SELECTION HEADER .  `setup.py` and
#: `tools/ratify.py` each write `GENERATED_DIR / CARRY_SELECTION_INC` for their own
#: run's arm scope, unconditionally overwriting whatever is there, before compiling
#: any translation unit that includes it.  See `carry_selection_header`.
GENERATED_DIR = ROOT / "build" / "generated"
CARRY_SELECTION_INC = "carry_selection.inc"
CARRY_PARTS_INC = "carry_parts.inc"

#: THE CARRY KERNEL'S PARTS (the composer's switches, KERNEL_STANDARDS §22 (9)): each names a
#: part of an MMA phase that a measurement build may replace by a STUB -- the part's HMMAs kept
#: with the same count, atom and accumulators, its other work gone. Production builds carry
#: every part; a build carrying fewer is an ITERATION build (never shippable).
CARRY_PARTS = ("readout.stream", "readout.loads", "readout.drain",
               "fold.pool", "fold.ring", "fold.loads")

BANNER = "// GENERATED by tools/gen_shards.py -- do not edit, regenerate.\n"

# ---------------------------------------------------------------------------
# THE CARRY ARM LIST -- one row per built arm, and THE list.  It is READ from
# `SHIPPED_SET_JSON`, the declared shipped set: this module owns the ENUMERATION
# (what a row means, which translation unit carries it, what the selection header and
# the manifest block say about it) and the declaration owns the MEMBERSHIP.
#
# A row is `(D, DV, warps_per_cta)` -- the routing depth, the value width and the CTA's
# warp count.  That is the whole key (KERNEL_STANDARDS §R11/§R16); the mode word, the stream counts and the
# park bit are RUNTIME, not arm axes, and the window and chunk are the descriptor's.
#
# THE DECLARATION IS EMPTY: the carry family has no kernels, so no arm is declared,
# there is no per-arm translation unit to generate, and every scope resolves to nothing.
# The table and the selection header it feeds are the BUILD's contract rather than the
# body's -- they describe the key and stay callable at zero rows -- so they hold the
# shape a body arrives into.


#: THE KEY, NAMED ONCE.  The declaration declares it, every refusal below quotes it,
#: and `arm_switch`'s generated set is built from it in the same order.
ARM_KEY: tuple[str, ...] = ("D", "DV", "warps_per_cta")


class ShippedSetError(SystemExit):
    """A declaration this generator refuses, with the field named.

    A `SystemExit` because every consumer (`setup.py`, `tools/ratify.py`, the lints,
    this CLI) wants the same outcome from a malformed declaration -- stop, with the
    reason on stdout -- and none of them has a recovery for it.
    """


def _load_shipped_set(path: Path = SHIPPED_SET_JSON) -> dict:
    """The declaration, READ AND REFUSED FIELD BY FIELD.

    Everything this checks is a way the declaration could be wrong that the build
    would otherwise discover as a compile error inside a generated file, or not at
    all: an unknown axis value, a duplicate row, a row in both lists, a row spelled
    out of canonical order (which would silently RENUMBER every arm index the
    selection header, the per-arm units and `ROLA_CARRY_ARMS` name).
    """
    if not path.exists():
        raise ShippedSetError(
            f"no declared shipped set at {path}. The carry family's arm table is a "
            f"DECLARATION, not a literal in this module; there is nothing to fall "
            f"back to.")
    try:
        blob = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise ShippedSetError(f"{path.name} is not readable as JSON: {exc}")

    if blob.get("schema") != 1:
        raise ShippedSetError(
            f"{path.name} declares schema {blob.get('schema')!r}; this generator "
            f"reads schema 1. A schema bump is a deliberate re-read of every "
            f"consumer, never a silent widening.")
    if blob.get("family") != "carry":
        raise ShippedSetError(
            f"{path.name} declares family {blob.get('family')!r}; this file is the "
            f"CARRY family's declaration.")
    if blob.get("key") != list(ARM_KEY):
        raise ShippedSetError(
            f"{path.name} declares the key {blob.get('key')!r}, but an arm is keyed "
            f"{list(ARM_KEY)} and nothing else (KERNEL_STANDARDS §R11: MO, the stream "
            f"counts and the park bit are runtime; the window and chunk are the "
            f"descriptor's). Re-key the declaration or amend the law first.")

    domains = blob.get("domains")
    if not isinstance(domains, dict) or sorted(domains) != sorted(ARM_KEY):
        raise ShippedSetError(
            f"{path.name}'s `domains` must name exactly the key's fields "
            f"{sorted(ARM_KEY)}, got {sorted(domains) if isinstance(domains, dict) else domains!r}")
    for field in ARM_KEY:
        values = domains[field]
        if not isinstance(values, list) or not values or not all(
                isinstance(v, int) for v in values):
            raise ShippedSetError(
                f"{path.name}: domain of {field} is {values!r}; it must be a "
                f"non-empty list of integers")

    rows: list[tuple] = []
    seen: dict[tuple, str] = {}
    for which in ("shipped", "test"):
        declared = blob.get(which)
        if not isinstance(declared, list):
            raise ShippedSetError(
                f"{path.name} has no `{which}` list. An empty declaration is written "
                f"`[]`; a missing one cannot be told from a typo.")
        for row in declared:
            if (not isinstance(row, list) or len(row) != len(ARM_KEY)
                    or not all(isinstance(v, int) for v in row)):
                raise ShippedSetError(
                    f"{path.name}: `{which}` row {row!r} is not "
                    f"{list(ARM_KEY)} as {len(ARM_KEY)} integers")
            key = tuple(row)
            for field, value in zip(ARM_KEY, key):
                if value not in domains[field]:
                    raise ShippedSetError(
                        f"{path.name}: `{which}` row {list(key)} has {field}={value}, "
                        f"which is not in the declared domain {domains[field]}")
            if key in seen:
                raise ShippedSetError(
                    f"{path.name}: row {list(key)} is declared twice "
                    f"(`{seen[key]}` and `{which}`). An arm is shipped or it is a "
                    f"test arm; it is never both, and a duplicate would give one "
                    f"kernel two indices.")
            seen[key] = which
            rows.append(key)

    canonical = sorted(rows)
    if rows != canonical:
        raise ShippedSetError(
            f"{path.name}: the rows are not in canonical order. An arm's INDEX is "
            f"named by the selection header, by the per-arm translation units and by "
            f"ROLA_CARRY_ARMS, so it must be a property of the declaration and not of "
            f"where a row was typed. Write `shipped` then `test`, each sorted, so "
            f"that the concatenation is sorted:\n"
            f"    {[list(r) for r in canonical]}")

    return {"rows": tuple(rows),
            "test": tuple(i for i, r in enumerate(rows) if seen[r] == "test"),
            "domains": {k: tuple(v) for k, v in domains.items()},
            "path": path}


_DECLARED = _load_shipped_set()

#: THE ARM TABLE, in declaration order.  `CARRY_ARMS[i]` is arm `i` everywhere.
CARRY_ARMS: tuple = _DECLARED["rows"]

#: THE SHIPPED / TEST SPLIT.  A default build compiles the SHIPPED rows only;
#: a TEST row is built for the battery and never shipped.  Both are empty while the
#: declaration is: a build carries no carry arm at all.
CARRY_TEST_ARMS: tuple = _DECLARED["test"]
CARRY_SHIPPED_ARMS: tuple = tuple(i for i in range(len(CARRY_ARMS))
                                  if i not in CARRY_TEST_ARMS)


def declaration_matches_table() -> list[str]:
    """RE-READ the declaration and compare it to this module's table.

    The point of the round trip is that the two statements are independent: the table
    was built at import time from the file as it was THEN, and the post-build check
    (`setup.py`) asks the question again against the file as it is NOW, after a build
    that may have run for an hour. It is also the only check that fires when something
    mutates the table after import.
    """
    fresh = _load_shipped_set()
    bad = []
    if fresh["rows"] != tuple(CARRY_ARMS):
        bad.append(f"    rows: the declaration says {[list(r) for r in fresh['rows']]}, "
                   f"the table says {[list(r) for r in CARRY_ARMS]}")
    if fresh["test"] != tuple(CARRY_TEST_ARMS):
        bad.append(f"    test rows: the declaration says {list(fresh['test'])}, "
                   f"the table says {list(CARRY_TEST_ARMS)}")
    return bad


def carry_kernel_key(row) -> tuple:
    """THE INSTANTIATION an arm's body IS -- and therefore what a TU may hold once.

    Two rows that key the same are ONE kernel and share a file; emitting one kernel
    from two objects is the state `tools/ratify.py` refuses by name.  On the final key
    a row IS its kernel: `(D, DV, warps_per_cta)` selects a body and nothing else does.
    """
    return tuple(row)


def carry_groups() -> dict[int, list[int]]:
    """`{owning arm index -> the arm indices its TU carries}`, in list order.

    The owner is the LOWEST index of the group, which is what names the file.
    """
    by_key: dict = {}
    for i, row in enumerate(CARRY_ARMS):
        by_key.setdefault(carry_kernel_key(row), []).append(i)
    return {members[0]: members for members in
            sorted(by_key.values(), key=lambda m: m[0])}


def carry_tu_of() -> dict[int, int]:
    """`{arm index -> the owning arm index whose file holds it}`."""
    return {i: owner for owner, members in carry_groups().items() for i in members}


def shard_manifest_block() -> dict:
    """The ratification's `shards` block: `{shard name: {members_sha256, count}}`.

    MEMBERSHIP ONLY -- no paths, no ordering -- so that re-filing the same
    measurements cannot move `tools/ratify.py`'s manifest digest while adding,
    dropping or moving one instantiation must (docs/ratification.md, "The `shards`
    block, and what it makes provable"). One shard per generated translation unit,
    named by the file that carries the group.

    EMPTY on this line, because the declared shipped set is: there is no per-arm unit,
    so there is no shard, so the block is `{}` -- which is what the committed manifests
    already record. This function is what produces that, rather than the manifests
    happening to carry an empty dict nobody writes.
    """
    out = {}
    for owner, members in carry_groups().items():
        blob = "\n".join(" ".join(str(x) for x in (i,) + tuple(CARRY_ARMS[i]))
                          for i in members).encode()
        out[f"carry_arm_{owner}"] = {
            "members_sha256": hashlib.sha256(blob).hexdigest(),
            "count": len(members)}
    return out


def carry_parts_header(parts) -> str:
    """THE GENERATED (never checked in) PARTS HEADER: `ROLA_CARRY_PARTS` as a bit mask over
    `CARRY_PARTS`, written on every build and every ratify run (a composer's stubbed mask left
    behind must never reach a gate). Included only by `carry/carry_kernel.cuh`."""
    bad = sorted(set(parts) - set(CARRY_PARTS))
    if bad:
        raise ValueError(f"carry_parts_header: no such part(s) {bad}; the parts are {CARRY_PARTS}")
    mask = sum(1 << CARRY_PARTS.index(x) for x in set(parts))
    lines = [BANNER, "// the CARRY KERNEL'S PARTS for this build: bit i is CARRY_PARTS[i] REAL.\n"]
    lines += [f"//   bit {i}: {name} {'real' if mask >> i & 1 else 'STUB'}\n" for i, name in enumerate(CARRY_PARTS)]
    lines.append(f"#define ROLA_CARRY_PARTS 0x{mask:x}u\n")
    return "".join(lines)


def carry_selection_header(arms) -> str:
    """THE GENERATED (never checked in) SELECTION HEADER.

    Renders `#define ROLA_CARRY_BUILT 1` plus one `#define ROLA_CARRY_BUILD_<i> 1`
    per index in `sorted(set(arms))`. Written by `setup.py` (from `ROLA_CARRY_ARMS`)
    and by `tools/ratify.py` (from the shipped set or a `--carry-arms`/`--arm` scope)
    to `GENERATED_DIR / CARRY_SELECTION_INC` on every run, UNCONDITIONALLY
    OVERWRITING whatever is there -- never accumulated across runs. Included ONLY by
    the carry family's checked-in arm include (the per-arm TUs and the carry dispatch
    TU reach it through that one file), never by anything else, so no other translation
    unit's argv or included content depends on the selection.

    An empty selection (`arms == []`) still emits the `ROLA_CARRY_BUILT` sentinel
    and zero `ROLA_CARRY_BUILD_<i>` lines: a build that selects nothing must still
    satisfy the dispatch TU's include-guard, not silently omit it.

    IT ALSO CARRIES THE ARM SET `arm_switch` DISPATCHES OVER -- the X-macro
    `ROLA_CARRY_ARM_SET_X(F)`, one `F(index, D, DV, warps_per_cta)` per SELECTED row in
    index order, with `ROLA_CARRY_ARM_COUNT` (how many this build carries) beside
    `ROLA_CARRY_ARM_DECLARED` (how many the declaration declares). Both counts, because
    the host refusal has to tell "your wheel does not carry that arm" from "nothing
    builds that arm in any configuration" -- the same distinction the battery's
    `require_arm` makes, and the reason an undeclared arm is never a skip.
    """
    n = len(CARRY_ARMS)
    bad = sorted({i for i in arms if not 0 <= i < n})
    if bad:
        raise ValueError(f"carry_selection_header: no such carry arm(s) {bad}; "
                         f"the list has {n} rows (0..{n - 1})")
    picked = sorted(set(arms))
    out = [BANNER,
           "// the CARRY ARM SELECTION for this build/ratify run. NEVER\n",
           "// CHECKED IN; regenerated by setup.py (from ROLA_CARRY_ARMS) and by\n",
           "// tools/ratify.py (from the shipped set or --arm scope) on every run.\n",
           "// Included only by the per-arm TUs and the carry dispatch TU.\n",
           "#define ROLA_CARRY_BUILT 1\n"]
    for i in picked:
        out.append(f"#define ROLA_CARRY_BUILD_{i} 1\n")
    out.append("\n// THE ARM SET, for common/arm_switch.cuh: one F(i, D, DV, "
               "warps_per_cta)\n// per BUILT arm, in index order. See "
               "docs/internals/common/arm_switch.md\n")
    out.append(f"#define ROLA_CARRY_ARM_COUNT {len(picked)}\n")
    out.append(f"#define ROLA_CARRY_ARM_DECLARED {n}\n")
    body = " \\\n".join(
        f"  F({i}, {CARRY_ARMS[i][0]}, {CARRY_ARMS[i][1]}, {CARRY_ARMS[i][2]})"
        for i in picked)
    if body:
        out.append("#define ROLA_CARRY_ARM_SET_X(F) \\\n" + body + "\n")
    else:
        out.append("//: NO ARM IS BUILT: the X-macro expands to nothing, "
                   "`ROLA_CARRY_ARM_COUNT` is 0,\n"
                   "//: and `arm_switch` refuses every call by naming the empty set. "
                   "That is the\n//: honest state of a family with no kernels, not a hole.\n"
                   "#define ROLA_CARRY_ARM_SET_X(F)\n")
    return "".join(out)


def carry_sources() -> list:
    """`{arm index -> the generated file that carries it}`, for `setup.py`."""
    tu = carry_tu_of()
    return {i: f"carry_arm_{tu[i]}.cu" for i in range(len(CARRY_ARMS))}


def carry_arm_unit(owner: int, members: list[int]) -> str:
    """One generated translation unit: the arm bodies its group carries.

    A unit defines an arm only when THIS build selected it, so an arm-subset build
    parses the file but instantiates nothing -- which is what makes the subset a file
    subset rather than a macro subset (KERNEL_STANDARDS section 7).
    """
    out = [BANNER.replace("regenerate.", f"regenerate; arm group {owner}."),
           "\n",
           '#include "carry/carry_arm.cuh"\n',
           '#include "carry_selection.inc"\n',
           "\n",
           "namespace rola::carry {\n",
           "\n"]
    for i in members:
        row = CARRY_ARMS[i]
        out.append(f"#if defined(ROLA_CARRY_BUILD_{i})\n")
        out.append(f"ROLA_CARRY_ARM_DEFINE({i}, {row[0]}, {row[1]}, {row[2]})\n")
        out.append("#endif\n")
    out.append("\n}  // namespace rola::carry\n")
    return "".join(out)


def generated() -> dict[str, str]:
    """Every file this generator owns: relative path -> content.

    One translation unit per arm GROUP -- rows that key the same kernel share a file --
    so an arm the build does not want is a file the build does not compile.

    The directory's `README.md` is listed as its own content: the mirror-doc lint exempts a
    generated directory only against that page, and listing it here is what stops `--write`
    from deleting the exemption it is standing on.
    """
    out = {f"carry_arm_{owner}.cu": carry_arm_unit(owner, members)
           for owner, members in carry_groups().items()}
    out["README.md"] = (OUT_DIR / "README.md").read_text()
    return out


_BUILT_LINE_RE = re.compile(r"^#define ROLA_CARRY_BUILT 1$")
_ARM_LINE_RE = re.compile(r"^#define ROLA_CARRY_BUILD_(\d+) 1$")


def _check_carry_selection_schema() -> list[str]:
    """Self-test for `carry_selection_header`.

    The generated selection header is never checked into the tree, so `--check`
    cannot diff it against a file on disk the way it does the instantiation
    shards; this instead asserts the GENERATOR's schema directly, for the two
    scopes a real build/ratify run actually uses ("all" and the shipped set) plus
    the empty-selection edge case.
    """
    bad: list[str] = []
    cases = {
        "all": list(range(len(CARRY_ARMS))),
        "shipped": list(CARRY_SHIPPED_ARMS),
        "empty": [],
    }
    for name, arms in cases.items():
        text = carry_selection_header(arms)
        #: THE SELECTION LINES ONLY. The header also carries the arm SET (checked
        #: by `_check_arm_set_schema` below), so a bare `#define` filter would count
        #: those and read every well-formed header as malformed.
        lines = [l for l in text.splitlines()
                 if l.startswith("#define ROLA_CARRY_BUILT")
                 or l.startswith("#define ROLA_CARRY_BUILD_")]
        want_n = 1 + len(arms)
        if len(lines) != want_n:
            bad.append(f"    carry_selection_header({name}): {len(lines)} #define "
                       f"lines, expected {want_n} (1 + {len(arms)} arms)")
            continue
        if not _BUILT_LINE_RE.match(lines[0]):
            bad.append(f"    carry_selection_header({name}): first #define line "
                       f"{lines[0]!r} is not the ROLA_CARRY_BUILT sentinel")
            continue
        seen: list[int] = []
        malformed = []
        for line in lines[1:]:
            m = _ARM_LINE_RE.match(line)
            if not m:
                malformed.append(line)
            else:
                seen.append(int(m.group(1)))
        if malformed:
            bad.append(f"    carry_selection_header({name}): malformed #define "
                       f"line(s): {malformed}")
            continue
        if len(seen) != len(set(seen)):
            bad.append(f"    carry_selection_header({name}): duplicate arm index "
                       f"in {seen}")
            continue
        if set(seen) != set(arms):
            bad.append(f"    carry_selection_header({name}): named indices "
                       f"{sorted(set(seen))} != requested {sorted(set(arms))}")
            continue
        bad += _check_arm_set_schema(name, arms, text)
    return bad


_COUNT_RE = re.compile(r"^#define ROLA_CARRY_ARM_COUNT (\d+)$", re.MULTILINE)
_DECLARED_RE = re.compile(r"^#define ROLA_CARRY_ARM_DECLARED (\d+)$", re.MULTILINE)
_SET_MEMBER_RE = re.compile(r"^  F\((\d+), (\d+), (\d+), (\d+)\)", re.MULTILINE)


def _check_arm_set_schema(name: str, arms, text: str) -> list[str]:
    """`ROLA_CARRY_ARM_SET_X` names EXACTLY the selected rows, with their key.

    The X-macro is what `arm_switch`'s generated set is built from, so a set that
    disagrees with the selection would give the host dispatch a different matrix from
    the one the per-arm translation units compiled -- two enumerations of one set,
    which is the drift shape this generator exists to prevent.
    """
    bad = []
    picked = sorted(set(arms))
    count = _COUNT_RE.search(text)
    declared = _DECLARED_RE.search(text)
    if count is None or int(count.group(1)) != len(picked):
        bad.append(f"    carry_selection_header({name}): ROLA_CARRY_ARM_COUNT is "
                   f"{count.group(1) if count else 'absent'}, expected {len(picked)}")
    if declared is None or int(declared.group(1)) != len(CARRY_ARMS):
        bad.append(f"    carry_selection_header({name}): ROLA_CARRY_ARM_DECLARED is "
                   f"{declared.group(1) if declared else 'absent'}, expected "
                   f"{len(CARRY_ARMS)}")
    if "#define ROLA_CARRY_ARM_SET_X(F)" not in text:
        bad.append(f"    carry_selection_header({name}): no ROLA_CARRY_ARM_SET_X, so "
                   f"a translation unit including this header would not compile")
        return bad
    members = [tuple(int(x) for x in m) for m in _SET_MEMBER_RE.findall(text)]
    want = [(i,) + tuple(CARRY_ARMS[i]) for i in picked]
    if members != want:
        bad.append(f"    carry_selection_header({name}): ROLA_CARRY_ARM_SET_X names "
                   f"{members}, expected {want}")
    return bad


#: THE MUTANTS `--self-test` REQUIRES A REFUSAL FOR, one per rule `_load_shipped_set`
#: states.  A reader that cannot be made to fail is not a reader (the vacuity
#: discipline `tools/ratify.py --self-test` runs on itself, applied here).
_DECLARATION_MUTANTS: tuple[tuple[str, dict, str], ...] = (
    ("schema bump", {"schema": 2}, "schema"),
    ("wrong family", {"family": "decode"}, "family"),
    ("re-keyed", {"key": ["D", "DV"]}, "keyed"),
    ("domain missing a field", {"domains": {"D": [1], "DV": [64]}}, "domains"),
    ("empty domain", {"domains": {"D": [], "DV": [64], "warps_per_cta": [8]}},
     "non-empty list"),
    ("row of the wrong width", {"shipped": [[2, 64]]}, "as 3 integers"),
    ("value outside its domain", {"shipped": [[2, 48, 8]]},
     "not in the declared domain"),
    ("a row declared twice", {"shipped": [[2, 64, 8]], "test": [[2, 64, 8]]},
     "declared twice"),
    ("rows out of canonical order", {"shipped": [[2, 64, 8], [1, 64, 8]]},
     "canonical order"),
    ("a missing list", {"shipped": None}, "no `shipped` list"),
)


def _self_test() -> int:
    """Prove the declaration reader refuses, and the generator renders a real table.

    Two halves, because they fail differently: the MUTANTS prove no malformed
    declaration is quietly accepted, and the SYNTHETIC TABLE proves the selection
    header, the arm set and the shard block actually render rows -- which the live
    declaration, being empty, cannot show.
    """
    import copy
    import tempfile

    base = json.loads(SHIPPED_SET_JSON.read_text())
    bad = []
    with tempfile.TemporaryDirectory(prefix="rola_shipped_set_") as tmp:
        path = Path(tmp) / "shipped_set.json"
        for name, patch, needle in _DECLARATION_MUTANTS:
            blob = copy.deepcopy(base)
            for k, v in patch.items():
                if v is None:
                    blob.pop(k, None)
                else:
                    blob[k] = v
            path.write_text(json.dumps(blob))
            try:
                _load_shipped_set(path)
            except ShippedSetError as exc:
                if needle not in str(exc):
                    bad.append(f"    {name}: refused, but the message does not name "
                               f"{needle!r}: {exc}")
                continue
            bad.append(f"    {name}: ACCEPTED. The reader must refuse it.")
        path.unlink(missing_ok=True)
        if not path.exists():
            try:
                _load_shipped_set(path)
                bad.append("    a missing declaration: ACCEPTED")
            except ShippedSetError:
                pass

    #: A SYNTHETIC TABLE, installed on the module for the render checks only. The
    #: live declaration is empty, so nothing else in this file ever exercises a row.
    global CARRY_ARMS, CARRY_TEST_ARMS, CARRY_SHIPPED_ARMS
    saved = (CARRY_ARMS, CARRY_TEST_ARMS, CARRY_SHIPPED_ARMS)
    CARRY_ARMS = ((1, 64, 8), (2, 64, 8), (2, 128, 4))
    CARRY_TEST_ARMS = (2,)
    CARRY_SHIPPED_ARMS = (0, 1)
    try:
        bad += _check_carry_selection_schema()
        text = carry_selection_header([0, 2])
        for want in ("#define ROLA_CARRY_ARM_COUNT 2",
                     "#define ROLA_CARRY_ARM_DECLARED 3",
                     "  F(0, 1, 64, 8)", "  F(2, 2, 128, 4)"):
            if want not in text:
                bad.append(f"    the rendered arm set is missing {want!r}")
        if "  F(1, 2, 64, 8)" in text:
            bad.append("    the rendered arm set names arm 1, which this scope "
                       "does not build")
        block = shard_manifest_block()
        if sorted(block) != ["carry_arm_0", "carry_arm_1", "carry_arm_2"]:
            bad.append(f"    the shard block names {sorted(block)}, expected one "
                       f"shard per row")
        if any(b["count"] != 1 for b in block.values()):
            bad.append(f"    a shard block entry does not carry its membership "
                       f"count: {block}")
    finally:
        CARRY_ARMS, CARRY_TEST_ARMS, CARRY_SHIPPED_ARMS = saved

    #: THE PARTS HEADER: every part real is the full mask, a subset its bits, a stranger refused.
    if f"0x{(1 << len(CARRY_PARTS)) - 1:x}u" not in carry_parts_header(CARRY_PARTS):
        bad.append("    carry_parts_header(all): not the full mask")
    if "#define ROLA_CARRY_PARTS 0x8u" not in carry_parts_header(["fold.pool"]):
        bad.append("    carry_parts_header(['fold.pool']): not bit 3 alone")
    try:
        carry_parts_header(["readout.nothing"])
        bad.append("    carry_parts_header: accepted an unknown part")
    except ValueError:
        pass
    if bad:
        print("SELF-TEST FAILED:")
        print("\n".join(bad))
        return 1
    print(f"self-test OK  {len(_DECLARATION_MUTANTS)} declaration mutants refused by "
          f"name, a missing declaration refused, and the selection header, arm set "
          f"and shard block render a 3-row table")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="regenerate the tree")
    ap.add_argument("--check", action="store_true",
                    help="regenerate into memory and fail on any difference")
    ap.add_argument("--self-test", action="store_true",
                    help="prove the declaration reader refuses every malformed "
                         "shipped set, and that a non-empty table renders")
    a = ap.parse_args()
    if a.self_test:
        if a.write or a.check:
            raise SystemExit("--self-test is its own mode")
        return _self_test()
    if a.write == a.check:
        raise SystemExit("pass exactly one of --write / --check / --self-test")

    want = generated()
    if a.write:
        #: THE GENERATED TREE, INCLUDING THE SELECTION HEADER, IS ONE SHARED
        #: OUTPUT (LOCKS brief item 3): `tools/ratify.py` writes the same
        #: `CARRY_SELECTION_INC` path unconditionally on every build, so this
        #: CLI's own `--write` must not interleave with that write either.
        with host_budget.file_lock("carry_selection_header"):
            OUT_DIR.mkdir(parents=True, exist_ok=True)
            for name in sorted({p.name for p in OUT_DIR.iterdir() if p.is_file()}):
                if name not in want and name != ".gitkeep":
                    (OUT_DIR / name).unlink()
                    print(f"removed stale {name}")
            for name, text in sorted(want.items()):
                (OUT_DIR / name).write_text(text)
        print(f"wrote {len(want)} files to {OUT_DIR.relative_to(ROOT)}")
        return 0

    bad = []
    on_disk = ({p.name for p in OUT_DIR.iterdir() if p.is_file() and p.name != ".gitkeep"}
               if OUT_DIR.is_dir() else set())
    for name in sorted(on_disk - set(want)):
        bad.append(f"    {name}: on disk, not generated")
    for name, text in sorted(want.items()):
        path = OUT_DIR / name
        if not path.exists():
            bad.append(f"    {name}: missing")
        elif path.read_text() != text:
            bad.append(f"    {name}: differs from the generated content")
    if bad:
        print("FAIL  the checked-in instantiation shards do not match the arm "
              "list in tools/gen_shards.py:")
        print("\n".join(bad))
        print("\n    python tools/gen_shards.py --write")
        return 1

    selection_bad = _check_carry_selection_schema()
    if selection_bad:
        print("FAIL  carry_selection_header's schema self-test failed (the "
              "generated selection header is never checked in, so this asserts "
              "the generator directly):")
        print("\n".join(selection_bad))
        return 1

    print(f"shards OK  {len(want)} generated files match the {len(CARRY_ARMS)}-row "
          "arm list; carry_selection_header schema OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
