"""THE DUAL-RUN PROTOCOL: no change to the crown jewels lands without it.

    python tools/oracle_dual_run.py --surface producer --against HEAD~1
    python tools/oracle_dual_run.py --surface oracle   --against HEAD~1 --json run.json
    python tools/oracle_dual_run.py --surface producer --against HEAD~1 --mutate strides

The oracle pair -- `rola/ops/naive.py` and the routing references it composes with --
is what every Tier 1 gate is anchored to. A change to it cannot be reviewed by
reading the diff, because the question is never "is the new code reasonable" but "does
it compute the same function". So both versions are RUN, over a declared matrix, and
compared.

**THE OLD SIDE IS THE PARENT COMMIT'S REAL CODE.** It is checked out into a throwaway
git worktree and run in a SUBPROCESS with that tree on `PYTHONPATH` -- never
re-implemented, never copy-pasted, and never imported under an alias into this
process, where one stale `sys.modules` entry would silently compare a tree against
itself. Everything CPU and fp64: the references are pure torch, so no build is
involved and no device is touched.

**THE MATRIX IS GENERATED BY THIS FILE, AT THIS COMMIT, FOR BOTH SIDES.** The old
tree supplies the library; it never supplies the inputs. Same generator, same seeds,
one library swapped -- which is the only construction under which a difference is
attributable.

Two surfaces, because the two steps of the decomposition have different contracts:

* `--surface producer` -- the routing reference: entmax values, the support SET, the
  VJP, and the composed `routing_factors` / `union_split`. Compared under the
  PRODUCER CONTRACT: `max|dp| <= 1e-13`, `max|dz| <= 1e-13`, and support sets
  equal EXACTLY. Bit-identity is deliberately NOT required here -- the declared
  purpose of that step is to replace a bisection with a third party's closed form,
  so agreement to 1e-14 is the result, and the support-set equality is the claim with
  teeth (a threshold that moves by one entry is a routing change, not rounding).
* `--surface oracle` -- `naive_rola` itself, FORWARD AND BACKWARD. Compared BY
  BIT-IDENTITY: both sides run fp64 on identical inputs, so a rewrite that only
  nearly reproduces the old one has changed the definition. Declared exceptions are
  named on the command line (exact key, or a `fnmatch` pattern) and asserted
  individually; anything undeclared is a failure.

**THE BACKWARD HALF IS P3, AND IT IS NOT OPTIONAL.** A seeded VJP per cell over every
operand, with `None` recorded as `None` rather than coerced to zeros -- because the
oracle's `.detach()` at the clock is its literal spec, and the difference between "no
gradient" and "a zero gradient" is precisely what a manufactured graph edge hides. The
clock's detachment is observed through the WRITE levels, which under the bf16-bundle
ruling are the stored form: the `clock` mutant removes the `.detach()` and the write
levels' gradient moves.

**P5, NON-VACUITY.** `--mutate` injects a known defect into the NEW side and the run
must FAIL. A protocol that cannot fail is not a protocol, and this one is the gate
that stands between a quiet oracle change and every Tier 1 claim in the repository.

**P7, THE COUNT.** Every run asserts it compared at least `MINIMUM_COMPARISONS`
quantities and fails RED otherwise: a gate that cannot run must say so, not report a
verdict over whatever survived.
"""
from __future__ import annotations

import argparse
import contextlib
import fnmatch
import json
import subprocess
import sys
import tempfile
from pathlib import Path

import torch

ROOT = Path(__file__).resolve().parents[1]


def bind_library(root: Path, label: str) -> Path:
    """Import `rola` FROM `root`, and refuse to run if that is not what happened.

    **THIS IS THE TRAP THAT MAKES A DUAL RUN VACUOUS, AND IT IS REAL, NOT
    HYPOTHETICAL.** `rola` is installed editable, so `import rola` resolves through
    the install's path entry -- which names the CANONICAL checkout. Run as a script
    from a worktree, `sys.path[0]` is the script's own directory (`tools/`), the
    worktree's root is on no path at all, and both sides of the protocol quietly
    import the same canonical tree. Every comparison then passes, having compared
    nothing. Measured: from a sibling worktree (`/path/to/worktrees/<name>`),
    `python tools/...py` imported the CANONICAL checkout's `rola/__init__.py`
    instead of its own.

    The library each side must use is therefore named explicitly and CHECKED after
    the import, not merely arranged for. A path insertion that fails to take effect
    is exactly as silent as no insertion at all; the assertion is what makes it
    loud, and the printed path is what puts it in the record.
    """
    root = root.resolve()
    sys.path.insert(0, str(root))
    import rola

    actual = Path(rola.__file__).resolve()
    if root not in actual.parents:
        raise SystemExit(
            f"the {label} side imported {actual}, not the tree at {root} -- the "
            f"comparison would be between that tree and itself")
    print(f"{label} library: {actual.parent}")
    return actual.parent


#: the thresholds, from the measured agreement with one decade of headroom
#: (workflows/refactor/p07_audit.md section 3.2: worst 1.42e-14 forward, 6.66e-16 VJP).
#: The SUPPORT-SET claim carries no tolerance at all, by construction.
PRODUCER_ATOL = 1e-13

#: The bound a REASSOCIATED quantity is held to instead of bit-identity.
#:
#: Reassociation is the one difference a rewrite can legitimately introduce: the
#: same sum, added up in a different order. Its size is bounded by the length of
#: the sum times the unit roundoff, and the longest sum here is over the leaves,
#: `N <= 4096` in the matrix -- so `N * 2^-53 = 4.5e-13`. `1e-12` is that with a
#: factor of two of headroom, and it is RELATIVE, because the quantities span many
#: decades. A difference that does not fit is not reassociation.
REASSOCIATION_RTOL = 1e-12

#: fp64 seeds. Fixed here rather than passed in: a matrix whose inputs depend on the
#: caller is a matrix two runs can disagree about without either being wrong.
SEED = 20260805

#: How many slices the matrix runs in by default.
#:
#: THE UNCHUNKED RUN IS A HOST HAZARD, not merely a large one. The backward retains
#: one autograd graph per token per cell and the largest cells are `64x64` (N = 4096
#: leaves) at `T = 64`; run whole, the protocol peaked near 18 GB on a 23 GB machine
#: shared with build lanes and drove it into swap twice. Measured peak RSS of the
#: whole run (parent plus the old side), against an unchanged tree:
#:
#:     chunks=1   ~18 GB    (froze the host)
#:     chunks=4    13.0 GB  0:58
#:     chunks=16    4.6 GB  1:49
#:
#: 16 buys the headroom at 51 s. CHUNKING PROVABLY CANNOT CHANGE THE NUMBERS: the
#: inputs are drawn for every cell at every chunk count and only the oracle call is
#: skipped, and it is checked rather than argued -- the union over `chunks=4` and the
#: union over `chunks=8` are the same 1328 quantities, bit-identical, 0 mismatches.
DEFAULT_CHUNKS = 16

#: THE FLOOR ON WHAT A RUN MUST HAVE COMPARED, per surface, and a run that produces
#: fewer quantities FAILS RED. Measured (`oracle` 640, `producer` 162) and
#: raised whenever the matrix grows: a gate must prove it COMPARED, because a matrix
#: that quietly stopped emitting rows -- an axis that raises in the generator, a cell
#: that returns nothing -- reports PASS over whatever survived, and this protocol is
#: what stands between a quiet oracle change and every Tier 1 claim in the tree. The
#: precedent is real: the `oracle` surface was UNRUNNABLE for a window after `raw`
#: died and nothing said so.
#:
#: LOWERED ONCE, from `oracle` 640 to 512: the `write_levels_stored`
#: operand left the oracle's signature under R1 (the producer emits the stored form),
#: and the 128 `*/dstored{0,1}` gradients it contributed were `None` on both sides by
#: construction. The shim that kept passing it existed to span exactly the python
#: commits and is gone with it; what remains is the same matrix minus a vacuous
#: operand, which is why this is a legitimate shrink and not a lost row.
MINIMUM_COMPARISONS = {"oracle": 512, "producer": 162}


# ---------------------------------------------------------------------------
# THE MATRIX
# ---------------------------------------------------------------------------

def _producer_cells():
    """`(name, logits, mask, alpha)` over logit scale x width x masking.

    The scales are the audit's: 0.5 is a nearly-dense simplex, 3 is the working
    regime, 30 is where a bisection's finite iteration count shows and where two
    implementations are most likely to disagree about the support boundary.
    """
    g = torch.Generator().manual_seed(SEED)
    for width in (3, 16, 256):
        for scale in (0.5, 3.0, 30.0):
            z = torch.randn(8, width, generator=g, dtype=torch.float64) * scale
            for masked in (False, True):
                mask = None
                if masked:
                    mask = torch.ones(8, width, dtype=torch.bool)
                    #: A ragged mask, not a uniform one: padding past `b` is what the
                    #: kernel's `bmask` does, and a uniform mask would exercise none
                    #: of the boundary the mask exists for.
                    for row in range(8):
                        mask[row, max(1, width - row % width):] = False
                for alpha in (1.5, 2.0):
                    yield (f"w{width}-s{scale}-{'masked' if masked else 'dense'}-a{alpha}",
                           z.clone(), mask, alpha)


def _routing_cells():
    """`(name, read_logits, write_logits, mask)` for the COMPOSED reference."""
    g = torch.Generator().manual_seed(SEED + 1)
    for width in (4, 16):
        for scale in (0.5, 3.0, 30.0):
            r = torch.randn(2, 5, width, generator=g, dtype=torch.float64) * scale
            w = torch.randn(2, 5, width, generator=g, dtype=torch.float64) * scale
            yield (f"union-w{width}-s{scale}", r, w, None)


# ---------------------------------------------------------------------------
# THE OLD/NEW SIDE (whichever library is on sys.path)
# ---------------------------------------------------------------------------


def _levels(types, widths):
    """One softmax routing level per width.

    The oracle takes ALREADY-NORMALIZED simplices, so the activation choice never
    reaches it -- softmax is here because a topology requires one, and matching Tier 1
    keeps the two matrices talking about the same object.
    """
    dense = types.SoftmaxActivation()
    return tuple(types.IndependentRouting(width=w, read=dense, write=dense) for w in widths)


def _call(fn, **kwargs):
    """Call `fn` with the arguments it actually accepts, and only those.

    The protocol compares SEMANTICS across a change that may move the API -- removing
    a solver's iteration count is exactly such a change, and it is one of the things
    under test. Binding by signature is what lets the two sides be asked the same
    question through two different spellings; it is not a fallback, because the
    quantity compared afterwards is unchanged and every dropped argument is one this
    version does not have.
    """
    import inspect

    accepted = inspect.signature(fn).parameters
    return fn(**{k: v for k, v in kwargs.items() if k in accepted})


def emit_producer() -> dict:
    """Every producer quantity, from whichever `rola` is importable."""
    from rola.routing.entmax.reference import entmax, entmax_forward
    from rola.routing.reference import _union_split_with_support, union_split

    #: The old reference's own routing-level iteration count, passed only where the
    #: parameter still exists. `rola/routing/reference.py` used 80 before the swap.
    iters = {"n_iter": 80}

    out: dict[str, torch.Tensor] = {}
    for name, z, mask, alpha in _producer_cells():
        p, support, tau = _call(entmax_forward, z=z, alpha=alpha, dim=-1, mask=mask,
                                **iters)
        out[f"{name}/p"] = p
        out[f"{name}/support"] = support
        out[f"{name}/tau"] = tau
        #: The VJP through the PUBLIC entry point, with a seeded cotangent -- the
        #: backward is half of what a reference promises and the card's backward
        #: conformance depends on it.
        zg = z.clone().requires_grad_(True)
        pv = _call(entmax, z=zg, alpha=alpha, dim=-1, mask=mask, **iters)
        dp = torch.linspace(-1.0, 1.0, pv.numel(), dtype=torch.float64).reshape(pv.shape)
        (dz,) = torch.autograd.grad(pv, zg, grad_outputs=dp)
        out[f"{name}/dz"] = dz

    for name, r, w, mask in _routing_cells():
        read, write = _call(union_split, read_logits=r, write_logits=w, alpha=1.5,
                            mask=mask, **iters)
        out[f"{name}/read"] = read
        out[f"{name}/write"] = write
        #: The PACKED support is captured through the private entry point on
        #: purpose: it is the reference's wire format, and a packing change that the
        #: semantic outputs cannot see is exactly what the kernel would then be
        #: gated against.
        out[f"{name}/packed"] = _call(_union_split_with_support, read_logits=r,
                                      write_logits=w, alpha=1.5, mask=mask, **iters)[2]
    return out


#: the marker for "this input received NO gradient". An empty tensor rather than a
#: zero one, because the whole point of the backward half is that `None` and `0.0`
#: are DIFFERENT answers: `.detach()` at the clock is the oracle's literal spec, and
#: a manufactured graph edge that turns the refusal into a zero is exactly the defect
#: audit finding F1 names. A shape mismatch is then how the comparison reports it.
NO_GRAD = torch.zeros(0, dtype=torch.float64)


def emit_oracle(chunk: int = 0, chunks: int = 1) -> dict:
    """`naive_rola`'s outputs over the structural matrix, forward and backward.

    `chunk`/`chunks` select every `chunks`-th cell. THE INPUTS ARE DRAWN FOR EVERY
    CELL REGARDLESS -- only the oracle call is skipped -- so the generator reaches
    each cell in the same state at every chunk count, and a run split four ways
    compares the same numbers as a run split none ways. Chunking exists for peak
    memory (the backward retains one graph per token) and must not be able to
    change what is measured.
    """
    import rola.routing.types as types
    from rola.ops.naive import naive_rola
    from rola.routing.types import LeafMassDecay, Topology

    out: dict[str, torch.Tensor] = {}
    g = torch.Generator().manual_seed(SEED + 2)

    def simplex(shape):
        x = torch.rand(shape, generator=g, dtype=torch.float64) + 1e-3
        return x / x.sum(dim=-1, keepdim=True)

    #: The structural rectangles, the two `d_v`, decay off and on, and the
    #: tile-boundary/ragged `T` values. Named adversarial corners are mandatory rows,
    #: not options (the card's fixture design).
    #:
    #: THERE IS ONE NORMALIZATION AXIS VALUE, AND THAT IS NOT A NARROWING. `raw` is a
    #: dead axis: `validate_normalization` refuses it, and `naive_rola` calls that
    #: validator on entry, so every `raw` row raised on BOTH sides -- and since the
    #: emit runs before the comparison, one raising row aborted the whole run. This
    #: surface was therefore unrunnable, not merely narrower, for as long as `raw`
    #: has been dead. Reviving `raw` revives its rows here in the same batch.
    normalization = "global"
    index = -1
    for widths in ((64, 64), (8, 8, 8, 16), (4, 4)):
        for d_v in (32, 64):
            for decay_on in (False, True):
                for T in (1, 17, 37, 64):
                    index += 1
                    B, H = 1, 2
                    #: BOUND BY SIGNATURE, because `d_v` left `Topology` for the
                    #: layer. The old side still declares the parameter and
                    #: is handed it; the new side does not and is not. The oracle
                    #: derives `d_v` from `v` on BOTH sides, so the two are asked
                    #: the same question through two spellings -- which is the
                    #: mechanism `_call` exists for.
                    topo = _call(
                        Topology, levels=_levels(types, widths), d_v=d_v)
                    read = tuple(simplex((B, T, H, w)) for w in widths)
                    write = tuple(simplex((B, T, H, w)) for w in widths)
                    v = torch.randn(B, T, H, d_v, generator=g, dtype=torch.float64)
                    g_write = torch.rand(B, T, H, generator=g, dtype=torch.float64) + 0.5
                    g_read = (None if normalization == "global"
                              else torch.rand(B, T, H, generator=g,
                                              dtype=torch.float64) + 0.5)
                    decay = None
                    if decay_on:
                        dials = tuple(
                            torch.rand(H, w, generator=g, dtype=torch.float64)
                            * 0.3 + 0.1 for w in widths)
                        decay = LeafMassDecay(dials=dials)
                    if index % chunks != chunk:
                        continue
                    name = (f"{'x'.join(map(str, widths))}-dv{d_v}-{normalization}-"
                            f"{'decay' if decay_on else 'nodecay'}-T{T}")
                    operands = _differentiable(
                        v=v, g_read=g_read, g_write=g_write, read=read,
                        write=write, dials=None if decay is None else decay.dials)
                    y, state = _call(
                        naive_rola, v=v, read_levels=read, write_levels=write,
                        g_read=g_read, g_write=g_write, topology=topo, decay=decay,
                        normalization=normalization, output_final_state=True)
                    out[f"{name}/y"] = y
                    out[f"{name}/state"] = state
                    out.update(_backward(name, y, state, operands))
    return out


def _differentiable(**named):
    """Flatten the oracle's operands into `{key: tensor}`, marking each for grad.

    Tuples are expanded per level; `None` operands (no read gain under `global`,
    no dials without decay) simply do not appear, so a cell's key set states which
    operands that cell HAS.
    """
    flat: dict[str, torch.Tensor] = {}
    for key, value in named.items():
        if value is None:
            continue
        items = value if isinstance(value, tuple) else (value,)
        for index, tensor in enumerate(items):
            label = key if not isinstance(value, tuple) else f"{key}{index}"
            tensor.requires_grad_(True)
            flat[label] = tensor
    return flat


def _backward(name: str, y, state, operands: dict) -> dict:
    """P3: one seeded VJP per cell, every operand, `None` recorded as `None`.

    The cotangents are `linspace`, not random: the generator's state must not
    depend on how many cells ran before this one, or a matrix edit silently
    re-seeds every backward in the run.
    """
    dy = torch.linspace(-1.0, 1.0, y.numel(), dtype=torch.float64).reshape(y.shape)
    dstate = torch.linspace(0.25, -0.75, state.numel(), dtype=torch.float64).reshape(state.shape)
    keys = sorted(operands)
    grads = torch.autograd.grad(
        outputs=(y, state), inputs=[operands[k] for k in keys],
        grad_outputs=(dy, dstate), allow_unused=True)
    return {f"{name}/d{key}": (NO_GRAD if grad is None else grad.detach())
            for key, grad in zip(keys, grads)}


#: `emit_producer` takes no chunk arguments: its matrix is 90 small quantities and
#: splitting it would buy nothing. The dispatch passes them only where they exist.
SURFACES = {"producer": emit_producer, "oracle": emit_oracle}


def _emit(surface: str, chunk: int, chunks: int) -> dict:
    if surface == "oracle":
        return emit_oracle(chunk=chunk, chunks=chunks)
    if chunk:
        return {}
    return emit_producer()


# ---------------------------------------------------------------------------
# THE MUTANTS
# ---------------------------------------------------------------------------

def apply_mutant(kind: str) -> None:
    """Inject a known defect into the NEW side. The run MUST then fail.

    Each mutant is one of the blind spots the protocol exists to cover, so a mutant
    that does not fail names a hole in the comparison rather than a harmless change.
    """
    if kind == "strides":
        #: THE LEAF-ADDRESS MAP, perturbed where the oracle actually reads it: its
        #: OWN derivation (`rola/ops/naive.py::_radix_strides`).
        #:
        #: This mutant used to reverse `Topology.radix_strides`, because the oracle
        #: imported it. It no longer does, so that perturbation
        #: now moves nothing here BY DESIGN -- and the inverted claim, that a wrong
        #: production stride leaves the oracle unmoved and therefore DISAGREEING
        #: with the kernel, is asserted where it belongs, in
        #: `tests/oracle/test_oracle_independence.py`. What this file must still be
        #: able to see is a change to the address map the oracle uses.
        import rola.ops.naive as naive

        original = naive._radix_strides
        naive._radix_strides = lambda widths: tuple(original(widths)[::-1])
    elif kind == "eps":
        #: The readout's epsilon changes the FUNCTION, not its accuracy.
        import rola.ops.naive as naive

        #: `eps` is KEYWORD-ONLY, so it lives in `__kwdefaults__`. Perturbing the
        #: default rather than the call sites is deliberate: it is the same thing a
        #: careless edit to the constant would do.
        naive.naive_rola.__kwdefaults__["eps"] = 2e-5
    elif kind == "clock":
        #: THE DETACHMENT AT THE CLOCK, removed. `c = stop_gradient(prod_l
        #: p_write_stored)` is the spec's own wording, so a gradient reaching the
        #: stored levels is a semantic change that the FORWARD cannot see at all --
        #: this is the mutant that says whether the backward half has teeth.
        #:
        #: Source-level, because the detachment is an expression inside the
        #: recurrence rather than a name that can be rebound. The module is
        #: re-executed in its own globals with the call removed; the count assert
        #: is what stops a future edit from making the mutant a no-op.
        import rola.ops.naive as naive

        source = Path(naive.__file__).read_text()
        if source.count(".detach()") != 1:
            raise SystemExit(
                f"the `clock` mutant expects exactly one `.detach()` in "
                f"{naive.__file__}, found {source.count('.detach()')}")
        namespace = dict(naive.__dict__)
        exec(compile(source.replace(".detach()", ""), naive.__file__, "exec"), namespace)
        naive.naive_rola = namespace["naive_rola"]
    elif kind == "support":
        #: One entry pushed out of the support: the claim P4 makes with no tolerance.
        import rola.routing.entmax.reference as ref

        inner = ref.entmax_forward

        def clipped(z, alpha, dim=-1, mask=None, **kw):
            p, support, tau = inner(z, alpha, dim=dim, mask=mask, **kw)
            flat = support.reshape(-1, support.shape[-1])
            for row in range(flat.shape[0]):
                idx = flat[row].nonzero()
                if idx.numel() > 1:
                    flat[row, idx[-1]] = False
                    break
            return p, support, tau

        ref.entmax_forward = clipped
    else:
        raise SystemExit(f"unknown mutant {kind!r}; known: strides, eps, clock, support")
    print(f"MUTANT ACTIVE: {kind}  (this run MUST fail)")


# ---------------------------------------------------------------------------
# THE COMPARISON
# ---------------------------------------------------------------------------

def _excepted(key: str, exceptions) -> bool:
    """A declared P2 exception matches by exact key or by `fnmatch` pattern.

    Patterns exist because an exception is usually a QUANTITY -- one gradient across
    every cell -- rather than one cell, and ninety-six spellings of the same
    declaration is a declaration nobody reads.
    """
    return any(key == e or fnmatch.fnmatch(key, e) for e in exceptions)


def _matches(key: str, patterns) -> bool:
    """Same matching rule, for the reassociation register."""
    return any(key == p or fnmatch.fnmatch(key, p) for p in patterns)


def compare(old: dict, new: dict, *, surface: str, exceptions: set,
            reassociated: set = frozenset()) -> dict:
    """One chunk's tally: how many quantities, the worst difference, the failures."""
    only_old = sorted(k for k in set(old) - set(new) if not _excepted(k, exceptions))
    only_new = sorted(k for k in set(new) - set(old) if not _excepted(k, exceptions))
    if only_old or only_new:
        return {"count": len(old), "worst": {"value": 0.0, "key": None},
                "failures": [(key, "answered by only one side")
                             for key in only_old + only_new]}

    worst = {"value": 0.0, "key": None}
    failures = []
    for key in sorted(old):
        a, b = old[key], new[key]
        quantity = key.rsplit("/", 1)[-1]
        if a.shape != b.shape:
            if not _excepted(key, exceptions):
                #: A gradient that appeared or vanished lands here, since NO_GRAD is
                #: the empty tensor: the message names the transition rather than a
                #: number, which is the only useful thing to say about it.
                failures.append((key, f"shape {tuple(a.shape)} -> {tuple(b.shape)}"))
            continue
        if a.dtype == torch.bool or quantity in ("support", "packed"):
            #: NO TOLERANCE. A support set or a packed word is a discrete claim; one
            #: entry moving is a routing change, not a rounding difference.
            if not torch.equal(a, b):
                differing = int((a != b).sum())
                failures.append((key, f"{differing} discrete entr(ies) differ"))
            continue
        if a.numel() == 0:
            #: Both sides answered `None` (the shapes already agree, so this is not a
            #: transition). There is no continuous quantity to compare and `max()`
            #: has no answer on an empty tensor; agreeing refusals agree.
            continue
        delta = (a.double() - b.double()).abs().max().item()
        if delta > worst["value"]:
            worst = {"value": delta, "key": key}
        if _matches(key, reassociated):
            #: DECLARED REASSOCIATION. Not an exemption: the quantity still has to
            #: agree, just under the bound a reordered sum can produce rather than
            #: under bit-identity. Anything larger is a changed definition wearing a
            #: rounding difference's clothes.
            scale = max(float(a.abs().max()), float(b.abs().max()), 1.0)
            if delta > REASSOCIATION_RTOL * scale:
                failures.append(
                    (key, f"max|d| = {delta:.3e} exceeds the reassociation bound "
                          f"{REASSOCIATION_RTOL * scale:.3e}"))
            continue
        if surface == "oracle" and not _excepted(key, exceptions):
            if not torch.equal(a, b):
                failures.append((key, f"not bit-identical, max|d| = {delta:.3e}"))
        elif delta > PRODUCER_ATOL:
            failures.append((key, f"max|d| = {delta:.3e} > {PRODUCER_ATOL:.0e}"))

    return {"count": len(old), "worst": worst, "failures": failures}


#: The OLD side's subprocess environment. `TORCHINDUCTOR_COMPILE_THREADS` is
#: pinned because torch fans out one compile worker per core on import and the
#: protocol runs two interpreters at once on a 23 GB host shared with build lanes;
#: nothing here is compiled, so the workers were pure overhead. `PATH` stays
#: minimal so the old tree cannot pick up a tool from the caller's shell.
OLD_SIDE_ENV = {"PATH": "/usr/bin:/bin", "TORCHINDUCTOR_COMPILE_THREADS": "4",
                "OMP_NUM_THREADS": "4"}


@contextlib.contextmanager
def _old_tree(ref: str):
    """`ref` checked out into a throwaway worktree, for the life of the run.

    One worktree for every chunk: checking out again per chunk would be the same
    tree fetched N times, and a tree that changed between chunks would silently
    make the chunks incomparable.
    """
    with tempfile.TemporaryDirectory(prefix="rola_dualrun_") as tmp:
        tree = Path(tmp) / "old"
        subprocess.run(["git", "-C", str(ROOT), "worktree", "add", "--detach",
                        str(tree), ref], check=True, capture_output=True, text=True)
        try:
            yield tree
        finally:
            subprocess.run(["git", "-C", str(ROOT), "worktree", "remove", "--force",
                            str(tree)], check=False, capture_output=True)


def _emit_old(tree: Path, ref: str, surface: str, out_path: Path,
              chunk: int, chunks: int) -> None:
    """Run this same file inside the old tree, against the old tree's library."""
    proc = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), "--surface", surface,
         "--emit", str(out_path), "--chunk", str(chunk), "--chunks", str(chunks),
         "--library", str(tree)],
        cwd=str(tree), env={"PYTHONPATH": str(tree), **OLD_SIDE_ENV},
        capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout + proc.stderr)
        raise SystemExit(f"the OLD side ({ref}) failed to run (chunk {chunk}/{chunks})")
    #: The old side's bound library is echoed once, on the first slice: the record
    #: has to name BOTH trees, or "the old side imported the old tree" is a claim
    #: about the code rather than about the run.
    if chunk == 0:
        for line in proc.stdout.splitlines():
            if line.startswith("OLD library:"):
                print(line)


def report(surface: str, tallies: list, exceptions: set,
           reassociated: set = frozenset()) -> bool:
    """One verdict over every chunk. A chunked run reads exactly like an unchunked one."""
    count = sum(t["count"] for t in tallies)
    worst = max((t["worst"] for t in tallies), key=lambda w: w["value"],
                default={"value": 0.0, "key": None})
    failures = [item for t in tallies for item in t["failures"]]
    rule = ("BIT-IDENTITY" if surface == "oracle"
            else f"producer contract (atol {PRODUCER_ATOL:.0e}, support sets exact)")
    floor = MINIMUM_COMPARISONS[surface]
    print(f"\n{count} quantities compared under {rule} (floor {floor})")
    print(f"worst continuous difference: {worst['value']:.3e}"
          + (f"  at {worst['key']}" if worst["key"] else ""))
    if exceptions:
        print(f"declared exceptions ({len(exceptions)}): {sorted(exceptions)}")
    if reassociated:
        print(f"declared reassociations ({len(reassociated)}, held to "
              f"{REASSOCIATION_RTOL:.0e} relative): {sorted(reassociated)}")
    if count < floor:
        print(f"\nFAIL  the run compared {count} quantities, below the {surface} "
              f"surface's floor of {floor}: this gate did not gate. Either the matrix "
              "lost rows (find them) or it legitimately shrank (move the floor, in the "
              "same commit, with the reason).")
        return False
    if failures:
        print(f"\nFAIL  {len(failures)} quantit(ies) disagree:")
        for key, why in failures[:12]:
            print(f"        {key}: {why}")
        if len(failures) > 12:
            print(f"        ... and {len(failures) - 12} more")
        return False
    print("PASS  dual run")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--surface", choices=sorted(SURFACES), required=True)
    ap.add_argument("--against", metavar="REF",
                    help="the commit whose oracle is the OLD side (e.g. HEAD~1)")
    ap.add_argument("--emit", metavar="PATH",
                    help="internal: write THIS tree's side and exit")
    ap.add_argument("--chunk", type=int, default=0, help="internal: which slice to emit")
    ap.add_argument("--library", metavar="TREE",
                    help="internal: the tree whose `rola` this side must import")
    ap.add_argument("--chunks", type=int, default=DEFAULT_CHUNKS,
                    help=f"slices to run the matrix in, one at a time "
                         f"(default {DEFAULT_CHUNKS}); bounds peak memory, "
                         f"changes nothing measured")
    ap.add_argument("--mutate", metavar="KIND",
                    help="P5: inject a known defect into the NEW side; the run must fail")
    ap.add_argument("--except", dest="exceptions", action="append", default=[],
                    metavar="KEY", help="a declared P2 exception (key or fnmatch), repeatable")
    ap.add_argument("--reassociated", action="append", default=[], metavar="KEY",
                    help="a quantity whose sum is reordered by the change under test: "
                         "held to REASSOCIATION_RTOL instead of bit-identity, never exempt")
    ap.add_argument("--json", metavar="PATH", help="write the record")
    a = ap.parse_args()

    if a.emit:
        bind_library(Path(a.library) if a.library else ROOT, "OLD" if a.library else "NEW")
        torch.save(_emit(a.surface, a.chunk, a.chunks), a.emit)
        return 0
    if not a.against:
        raise SystemExit("--against REF is required (the OLD side is a real commit)")
    if a.chunks < 1:
        raise SystemExit("--chunks must be at least 1")

    #: BEFORE the mutant, which imports `rola` to patch it: a mutant applied to the
    #: wrong tree is a mutant applied to the OLD side as well.
    bind_library(ROOT, "NEW")
    if a.mutate:
        apply_mutant(a.mutate)

    exceptions = set(a.exceptions)
    print(f"OLD = {a.against}   NEW = working tree   surface = {a.surface}"
          + (f"   chunks = {a.chunks}" if a.chunks > 1 else ""))
    tallies = []
    with _old_tree(a.against) as tree:
        for chunk in range(a.chunks):
            #: ONE CHUNK LIVE AT A TIME, on both sides. The old side's dict is
            #: dropped before the next subprocess starts and the new side's before
            #: the next chunk is built, so peak memory is the largest slice rather
            #: than the whole matrix twice.
            with tempfile.TemporaryDirectory(prefix="rola_dualrun_out_") as tmp:
                old_path = Path(tmp) / "old.pt"
                _emit_old(tree, a.against, a.surface, old_path, chunk, a.chunks)
                old = torch.load(old_path, weights_only=False)
            new = _emit(a.surface, chunk, a.chunks)
            tallies.append(compare(old, new, surface=a.surface, exceptions=exceptions,
                                   reassociated=set(a.reassociated)))
            del old, new

    ok = report(a.surface, tallies, exceptions, set(a.reassociated))
    if a.mutate:
        #: The mutant inverts the verdict: a mutant run that PASSES means the
        #: comparison is blind to the defect, which is the failure being tested for.
        if ok:
            print(f"\nP5 FAILED: the protocol PASSED with the {a.mutate!r} mutant "
                  f"active, so it cannot see that class of defect")
            return 1
        print(f"\nP5 PASSED: the protocol rejects the {a.mutate!r} mutant")
        ok = True

    if a.json:
        Path(a.json).write_text(json.dumps(
            {"old": a.against, "surface": a.surface, "mutant": a.mutate,
             "exceptions": sorted(exceptions), "chunks": a.chunks,
             "reassociated": sorted(set(a.reassociated)),
             #: EVERY failure, not the twelve that fit on a screen: the record is
             #: what a reviewer audits, and a truncated one cannot be joined to the
             #: tree.
             "failures": [[k, why] for t in tallies for k, why in t["failures"]],
             "quantities": sum(t["count"] for t in tallies),
             "worst": max((t["worst"]["value"] for t in tallies), default=0.0),
             "passed": ok}, indent=1, sort_keys=True) + "\n")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
